version: '2.4'
services:
  collector:
    build: collector
    volumes:
      - war:/home/war
  web:
    build: web
    volumes:
      - war:/opt/tomcat/webapps
    depends_on:
      - collector
    links:
      - collector
    ports:
      - "80:8080"
volumes:
  war: